### ISSUE TITLE
Support the syntax high light

### ISSUE THREAD

**Issue by cookgreen** [Phrohdoh/oraide#3]

**Comment by phrohdoh** [comment]
Syntax highlighting is absolutely planned!

**Comment by phrohdoh** [comment]
In https://github.com/Phrohdoh/oraide/commit/671c4e640bbb28ad1b7c5a9e2aac0c9c133a1cfd a grammar was added but it is a YAML grammar and not truly MiniYaml.

It should be good enough for a long while.

<details>
<summary>Screenshot showing syntax highlighting</summary>

<img width="1136" alt="Screen Shot 2019-07-15 at 8 48 42 AM" src="https://user-images.githubusercontent.com/4861023/61221152-799fa680-a6dd-11e9-8832-e25a84e86e2c.png">

</details>
